- name: make log directory
  file:
    path: "/var/log/hashbackup"
    state: directory
    owner: "{{ hb_user }}"
    group: "{{ hb_user }}"

- name: make log directory link
  file:
    src: "/var/log/hashbackup"
    dest: "{{ hb_backup_dir }}/logs"
    state: link

- name: cleanup hashbackup logs
  cron:
    user: "root"
    name: "cleanup hashbackup logs"
    hour: "06"
    minute: "04"
    job: /usr/bin/find /var/log/hashbackup/ -mtime +7 \( -name "*_retain" -o -name "*_backup" -o -name "*_selftest" \) -delete
  when: hb_cleanup_log == True
