---

- import_tasks: install.yml
  tags:
    - hb-install
    - hb
- import_tasks: config.yml
  tags:
    - hb-config
    - hb
  when: hb_config == True
- import_tasks: logging.yml
  tags:
    - hb-loggging
    - hb
  when: hb_symlink_log == True
- import_tasks: cron.yml
  tags:
    - hb-cron
    - hb
  when: hb_cron == True

